###
POST http://localhost:5544/mail
Content-Type: application/json

{
    
    "to": "rh@tarkuss.com.br",
    "company": "Tarkuss",
    "vacancy": "Desenvolvedor Fullstack",
    "nameRecruiter": "RH da Tarkuss",
    "skills": "JavaScript, TypeScript, React, NextJSTailwindCSS, Node.js, NestJS, Express, APIs REST, SOLID, Clean Code, Git, Docker, CI/CD, arquitetura limpa, microserviços, RabbitMQ, Kafka, Bancos SQL e NoSQL, Jenkins, Java, Spring Boot, JUnit e Mockito, infraestrutura em nuvem (AWS), versionamento, boas práticas de código e colaboração em equipe",
    "specialty":"Desenvolvedor Fullstack",
    "githubAvatar": "https://github.com/jnerydesigner.png",
    "nameFull": "Jander da Costa Nery",
    "pretention": "R$ 10.000",
    "availability": "Estou disponível para iniciar imediatamente e fico à disposição para entrevistas técnicas ou práticas."
}

###
POST http://localhost:5544/mail/db
Content-Type: application/json

{
    
    "to": "vagas@conecthus.org.br",
    "mail": "jander.webmaster@gmail.com",
    "company": "Conecthus",
    "vacancy": "Desenvolvedor Full Stack SR",
    "nameRecruiter": "Luciana Almeida"
}

